### PR TITLE
Fix typo in file suffix when loading name map *.mph

### PR DESCRIPTION
**Pull request by sebastian-nagel**

### CODE REVIEW

**Comment by mapio** [comment]
Thank you for the fix!

**Comment by sebastian-nagel** [comment]
Thanks!

Fyi: I've successfully managed to run pywebgraph using
- Jython 2.7.2
- Python 2.7
- Java 11
- webgraph 3.6.5
- (so far without using a renderer)

I wasn't able to run the Python module installer on Jython, so I had to launch pywebgraph.console by
```
java -Xmx... -Dpython.console=org.python.util.JLineConsole -Dpython.executable=/bin/python2.7 -cp ...webgraph_jar_and_dependencies:.../jython-standalone-2.7.2.jar: org.python.util.jython $PWD/pywebgraph/console.py
```

**Comment by mapio** [comment]
I was indeed curious to know if you were using the lib with up-to-date software.

What about updating the `README.md` to reflect your experience? If you prepare a pull request I'll gladly accept it!

**Comment by sebastian-nagel** [comment]
Yes, will do as soon as we (together with @Xue-Alex) get everything running. Ongoing work is found [here](https://github.com/Xue-Alex/commoncrawl_notebooks) and [here](https://gist.github.com/sebastian-nagel/95a086d7e8c76adc81d647258926e281). Unfortunately, Jython is limited to Python 2, so this work isn't really future-proof. If time we'll give [GraalVM's Jython emulator](https://github.com/graalvm/graalpython/blob/master/docs/user/Jython.md) a try.

**Pull request merged**
